import C from '../../shared/opcodes';

export default {
  [C.ADD]: '+',
  [C.CLX]: 'CL𝑥',
  [C.D0]: '0',
  [C.D1]: '1',
  [C.D2]: '2',
  [C.D3]: '3',
  [C.D4]: '4',
  [C.D5]: '5',
  [C.D6]: '6',
  [C.D7]: '7',
  [C.D8]: '8',
  [C.D9]: '9',
  [C.DIV]: '÷',
  [C.DECIMAL]: '•',
  [C.ENTER]: 'ENTER ↑',
  [C.EXP]: '𝑒<sup>𝑥</sub>',
  [C.MUL]: '×',
  [C.PI]: '𝜋',
  [C.POW]: '𝑥<sup>𝑦</sup>',
  [C.RECIPROCAL]: '<sup>1</sup>/𝑥',
  [C.ROLL_DOWN]: 'R↓',
  [C.SQRT]: '√𝑥',
  [C.SUB]: '-',
  [C.SWAP]: '𝑥↔︎𝑦',
};
